name: Aircraft Plotter
version: 0.1.0
slug: aircraft_plotter
description: Plots aircraft
stage: experimental
startup: application
init: false

arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386

panel_icon: mdi:cloud
panel_admin: false
#ingress_port: 8099

ingress: true
ports:
  80/tcp: 8099
#ports_description:
#  8099/tcp: Web interface (Not required for Ingress)

usb: true

map:
  - config:rw

options:
  device_port: 1
  message: "Aircraft Plotter..."
  HTML_SITE_LAT: HOMEASSISTANT_LATITUDE
  HTML_SITE_LON: HOMEASSISTANT_LONGITUDE
  HTML_SITE_ALT: HOMEASSISTANT_ELEVATION

schema:
  device_port: int(0,3)
  message: "str?"
  HTML_SITE_LAT: match([+-]?(([1-9][0-9]*)|(0))([.,][0-9]+)?|HOMEASSISTANT_LATITUDE)?
  HTML_SITE_LON: match([+-]?(([1-9][0-9]*)|(0))([.,][0-9]+)?|HOMEASSISTANT_LONGITUDE)?
  HTML_SITE_ALT: match([+-]?(([1-9][0-9]*)|(0))([.,][0-9]+)?|HOMEASSISTANT_ELEVATION)?
