build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:7.8.2
  amd64: ghcr.io/hassio-addons/debian-base/amd64:7.8.2
  armv7: ghcr.io/hassio-addons/debian-base/armv7:7.8.2

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Debian base"
  org.opencontainers.image.description: "debian"
  org.opencontainers.image.source: https://
  org.opencontainers.image.licenses: Apache License 2.0

args:
  TEMPIO_VERSION: 2021.09.0