# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: 0.0.31
slug: example
description: Example add-on
#url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false

panel_icon: mdi:cloud
panel_admin: false

ingress: true
ports:
  80/tcp: 80

ports_description:
  80/tcp: Web interface (Not required for Ingress)

usb: true

map:
  - config:rw

options:
  device_port: 1
  message: "Aircraft Plotter..."

schema:
  device_port: int(0,3)
  message: "str?"
