name: OpenWebRX
version: 0.0.23
slug: openwebrx
description: OpenWebRX
stage: experimental
startup: application
init: false

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

panel_icon: mdi:radio-tower
panel_admin: false

ingress: true
ingress_port: 8073

ports:
  8073/tcp: 8073
ports_description:
  8073/tcp: Web interface (Not required for Ingress)

usb: true

map:
  - config:rw

options:
  message: "OpenWebRX"
schema:
  message: "str?"
