name: stable-diffusion-webui
version: 0.0.08
slug: stable-diffusion-webui
description: WeeWX stable-diffusion-webui Add-on
stage: experimental
startup: application
init: false

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

panel_icon: mdi:cloud
panel_admin: false

ingress: true
ports:
  80/tcp: 80
ports_description:
  80/tcp: Web interface (Not required for Ingress)

map:
  - config:rw
