# https://github.com/rlang001/Home-Assistant-Addons/tree/master/rtl_tcp
name: RTL_TCP
version: "0.0.4"
slug: rtl_tcp
description: Runs rtl_tcp
url: "https://github.com/rlang001/Home-Assistant-Addons/tree/master/rtl_tcp"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
#map:
#  - share:rw

options:
  message: "Hello world..."
schema:
  message: "str?"
