name: RTL_CMD
version: 0.0.17
slug: rtl_cmd
description: rtl_cmd
stage: stable
startup: application
init: false

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

panel_icon: mdi:radio-tower
panel_admin: false

ingress: false


usb: true
map:
  - config:rw
