name: RTL_CMD
version: 0.0.15
slug: rtl_cmd
description: rtl_cmd
stage: experimental
startup: application
init: false

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

panel_icon: mdi:radio-tower
panel_admin: false

ingress: false
#ports:
#  80/tcp: 80
#ports_description:
#  80/tcp: Web interface (Not required for Ingress)

usb: true
#map:
#  - config:rw

#options:
#  message: "rtl_cmd"
#schema:
#  message: "str?"
