build_from:
  #aarch64: ghcr.io/home-assistant/aarch64-base-ubuntu:20.04
  amd64: ghcr.io/keeweb/keeweb:1.19.0-amd64
  armv7: ghcr.io/keeweb/keeweb:1.19.0-arm64
  

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Keeweb"
  org.opencontainers.image.description: "keeweb"
  org.opencontainers.image.source: https://
  org.opencontainers.image.licenses: Apache License 2.0

args:
  TEMPIO_VERSION: 2021.09.0

