name: Keeweb
version: 0.0.11
slug: keeweb
description: Keeweb Add-on
stage: experimental
startup: application
init: false

legacy: true

arch:
  - amd64

#panel_icon: mdi:cloud
panel_admin: false

ingress: true
ingress_port: 8099

#options:
#  "maintenance_mode": false

#schema:
#  "maintenance_mode": "bool?"

ports:
  80/tcp: 80
  443/tcp: 1443

ports_description:
  80/tcp: Web interface (Not required for Ingress)
  1443/tcp: Secure Web interface (Not required for Ingress)

map:
 - addon_config:rw
