build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-ubuntu:20.04
  amd64: ghcr.io/home-assistant/amd64-base-ubuntu:20.04
  armv7: ghcr.io/home-assistant/armv7-base-ubuntu:20.04


labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Ubuntu base"
  org.opencontainers.image.description: "ubuntu"
  org.opencontainers.image.source: https://
  org.opencontainers.image.licenses: Apache License 2.0

args:
  TEMPIO_VERSION: 2021.09.0
