name: WeeWX 5
version: 0.9.3
slug: weewx5
description: WeeWX 5 HA Add-on
stage: stable
startup: application
init: false

legacy: true

arch:
  - aarch64
  - amd64
  - i386

panel_icon: mdi:cloud
panel_admin: false

ingress: true
# ingress_port: 8099

options:
  "maintenance_mode": false

schema:
  "maintenance_mode": "bool?"

ports:
  80/tcp: 80

ports_description:
  80/tcp: Web interface (Not required for Ingress)

services:
  - mqtt:want

usb: true

map:
  - addon_config:rw
