
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:7.3.3
  amd64: ghcr.io/hassio-addons/debian-base/amd64:7.3.3
  armhf: ghcr.io/hassio-addons/debian-base/armhf:7.3.3
  armv7: ghcr.io/hassio-addons/debian-base/armv7:7.3.3
  i386: ghcr.io/hassio-addons/debian-base/i386:7.3.3

  # Alpine base
  #aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  #amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  #armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  #armv7: "ghcr.io/home-assistant/armv7-base:3.15"
  #386: "ghcr.io/home-assistant/i386-base:3.15"

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Simple Web Server add-on"
  org.opencontainers.image.description: "A Simple Webserver."
  org.opencontainers.image.source: "https://"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
