build_from:
  aarch64: ghcr.io/hassio-addons/ubuntu-base/aarch64:10.0.1
  amd64: ghcr.io/hassio-addons/ubuntu-base/amd64:10.0.1
  armv7: ghcr.io/hassio-addons/ubuntu-base/armv7:10.0.1
  i386: ghcr.io/hassio-addons/ubuntu-basei386-base:latest

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Ubuntu base"
  org.opencontainers.image.description: "ubuntu"
  org.opencontainers.image.source: https://
  org.opencontainers.image.licenses: Apache License 2.0

args:
  TEMPIO_VERSION: 2021.09.0
