name: WeeWX 5i
version: 0.4.42
slug: weewx5i
description: WeeWX 5i HA Add-on
stage: experimental
startup: application
init: false

legacy: true

arch:
  - aarch64
  - amd64
  - i386

panel_icon: mdi:cloud
panel_admin: false

ingress: true
ingress_port: 8099

ports:
  80/tcp: 80
  # 5000/tcp: 5000

ports_description:
  80/tcp: Web interface (Not required for Ingress)
  # 5000/tcp: Flask interface

usb: true

options:
  run_on_startup: false

schema:
  run_on_startup: bool

map:
  - addon_config:rw
  - share
  - ssl
# - homeassistant_config
# - addon_config
# - ssl
# - addons
# - backup
# - share
# - media
# - all_addon_configs
# - data.
