build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:6.2.6
  amd64: ghcr.io/hassio-addons/debian-base/amd64:6.2.6
  armv7: ghcr.io/hassio-addons/debian-base/armv7:6.2.6

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Debian Bullseye"
  org.opencontainers.image.description: "debian"
  org.opencontainers.image.source: https://
  org.opencontainers.image.licenses: Apache License 2.0

args:
  TEMPIO_VERSION: 2021.09.0
