build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.23
  amd64: ghcr.io/home-assistant/amd64-base:3.23
  armhf: ghcr.io/home-assistant/armhf-base:3.23
  armv7: ghcr.io/home-assistant/armv7-base:3.23
  i386: ghcr.io/home-assistant/i386-base:3.23


labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Alpine base"
  org.opencontainers.image.description: "alpine"
  org.opencontainers.image.source: https://
  org.opencontainers.image.licenses: Apache License 2.0

args:
  TEMPIO_VERSION: 2021.09.0
