build_from:
  aarch64: ghcr.io/hassio-addons/alpine-base/aarch64:3.2.3
  amd64: ghcr.io/hassio-addons/alpine-base/amd64:3.2.3

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Alpine base"
  org.opencontainers.image.description: "alpine"
  org.opencontainers.image.source: https://
  org.opencontainers.image.licenses: Apache License 2.0

args:
  TEMPIO_VERSION: 2021.09.0
