build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:9.1.0
  amd64: ghcr.io/hassio-addons/debian-base/amd64:9.1.0
  # armhf: ghcr.io/hassio-addons/debian-base/armhf:9.1.0
  # armv7: ghcr.io/hassio-addons/debian-base/armv7:9.1.0
  i386: ghcr.io/hassio-addons/debian-base/i386:9.1.0

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: RTL-433-2-MQTT"
  org.opencontainers.image.description: "RTL-433 2 MQTT"
  org.opencontainers.image.source: https://
  org.opencontainers.image.licenses: Apache License 2.0

args:
  TEMPIO_VERSION: 2021.09.0