---
name: Viewu Server
version: 0.1.5
slug: viewu_server
description: A Viewu Server in Home Assistant Add-on form.
stage: alpha
startup: application
init: false

# legacy: true
url: https://github.com/rlang001/Home-Assistant-Addons/edit/master/viewu_server_ha

arch:
  - amd64
  # - aarch64
  
auth_api: true

#watchdog: tcp://[HOST]:1883

discovery:
  - mqtt

options:
  mqtt_ip: 127.0.0.1
  mqtt_username: "mqtt_user"
  mqtt_password: "mqtt_password"
  mqtt_port: 1883

schema:
  mqtt_ip: str
  mqtt_username: str
  mqtt_password: str
  mqtt_port: int
  

services:
  - mqtt:need

