---
name: Viewu Server
version: 0.1.13
slug: viewu_server
description: A Viewu Server in Home Assistant Add-on form.
stage: experimental
startup: application
init: false

# legacy: true
url: https://github.com/rlang001/Home-Assistant-Addons/edit/master/viewu_server_ha

arch:
  - amd64
  # - aarch64
  
auth_api: true
services:
  - mqtt:need
  
#watchdog: tcp://[HOST]:1883
#discovery:
#  - mqtt

environment:
  MQTT_SERVER: "192.168.10.9"
  MQTT_PORT: "1883"
  MQTT_USER: "mqtt"
  MQTT_PASSWORD: "Sadie3Bail33"

options:
  host: 192.168.10.9
  username: "mqtt"
  password: "Sadi3Bail33"
  port: 1883

schema:
  host: str
  username: str
  password: str
  port: int
  



