---
name: Viewu Server
version: 0.1.9
slug: viewu_server
description: A Viewu Server in Home Assistant Add-on form.
stage: experimental
startup: application
init: false

# legacy: true
url: https://github.com/rlang001/Home-Assistant-Addons/edit/master/viewu_server_ha

arch:
  - amd64
  # - aarch64
  
auth_api: true

#watchdog: tcp://[HOST]:1883

discovery:
  - mqtt

options:
  host: 127.0.0.1
  username: "mqtt_user"
  password: "mqtt_password"
  port: 1883

schema:
  host: str
  username: str
  password: str
  port: int
  

services:
  - mqtt:need

