# Required configuration options
name: NOAA
version: 0.0.8
slug: noaa
description: NOAA HA Add-on
stage: experimental
startup: application
init: false
legacy: true

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386


#


map:
  # - config:rw
  - share:rw




